title: Accessing your Raspberry Pi via VNC
hero_image: images/banner.png
description: Access and use your Raspberry Pi with VNC
original_url: 
theme: cc-prototype
duration: 1
listed: false
copyedit: true
ingredient: true
interests: 
technologies: "vnc"
steps:
  - title: Using VNC
